module.exports = {
    img64: {
        src: {
            globs: 'images/*.{gif,png,jpg,jpeg,svg,ico}',
            options: {}
        },
        transform: {
            options: {},
            header: '',
            footer: ''
        },
        dest: {
            path: 'build',
            filename: 'images.js',
            header: 'module.exports = { // This file generated by gulp-imagine-64 at '
                + (new Date).toLocaleTimeString() + ' on '
                + (new Date).toLocaleDateString() + '\n',
            footer: '\n};\n',
            options: {}
        }
    }
};
